"""initial schema: auth + insurance core

Revision ID: 1caecab7bdde
Revises: 
Create Date: 2026-06-13 14:45:34.207637+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from services.security import hash_password

# revision identifiers, used by Alembic.
revision: str = '1caecab7bdde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (code, display name, resource, action) — gated by has_permission(code).
# admin/owner bypass the literal check, but the rows must exist.
PERMISSIONS = [
    ("customer.manage", "Manage customers", "customer", "manage"),
    ("product.manage", "Manage products", "product", "manage"),
    ("rate_table.load", "Load rate tables", "rate_table", "load"),
    ("policy.read", "Read policies", "policy", "read"),
    ("policy.manage", "Manage policies", "policy", "manage"),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('external_ref', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sex IN ('M','F')", name=op.f('ck_customers_sex_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_external_ref'), 'customers', ['external_ref'], unique=True)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_table('products',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('base','rider')", name=op.f('ck_products_kind_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('policies',
    sa.Column('policy_number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_policies_customer_id_customers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies'))
    )
    op.create_index(op.f('ix_policies_customer_id'), 'policies', ['customer_id'], unique=False)
    op.create_index(op.f('ix_policies_policy_number'), 'policies', ['policy_number'], unique=True)
    op.create_table('product_rating_dimensions',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('data_type', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_rating_dimensions_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_rating_dimensions')),
    sa.UniqueConstraint('product_id', 'name', name='dim_name')
    )
    op.create_index(op.f('ix_product_rating_dimensions_product_id'), 'product_rating_dimensions', ['product_id'], unique=False)
    op.create_table('rate_table_versions',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('unit_basis', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cell_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_rate_table_versions_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_table_versions'))
    )
    op.create_index(op.f('ix_rate_table_versions_product_id'), 'rate_table_versions', ['product_id'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permission_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permission_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permission'))
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_role_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_role_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_role'))
    )
    op.create_table('policy_coverages',
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sum_assured', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rate_table_version_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_policy_coverages_policy_id_policies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_policy_coverages_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rate_table_version_id'], ['rate_table_versions.id'], name=op.f('fk_policy_coverages_rate_table_version_id_rate_table_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_coverages')),
    sa.UniqueConstraint('policy_id', 'product_id', name='coverage_per_product')
    )
    op.create_index(op.f('ix_policy_coverages_policy_id'), 'policy_coverages', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_coverages_product_id'), 'policy_coverages', ['product_id'], unique=False)
    op.create_table('rate_cells',
    sa.Column('rate_table_version_id', sa.Integer(), nullable=False),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dim_key', sa.String(length=255), nullable=False),
    sa.Column('gross_before_discount', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('net_premium', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('gross_after_discount', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('discount', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rate_table_version_id'], ['rate_table_versions.id'], name=op.f('fk_rate_cells_rate_table_version_id_rate_table_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_cells')),
    sa.UniqueConstraint('rate_table_version_id', 'dim_key', name='cell_per_version')
    )
    op.create_index(op.f('ix_rate_cells_rate_table_version_id'), 'rate_cells', ['rate_table_version_id'], unique=False)
    # ### end Alembic commands ###

    # --- Postgres exclusion constraint: at most one active rate version per
    # product for any given effective date (NULL effective_to = +infinity).
    # Autogenerate can't emit this, so it's hand-added. ---
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(
        """
        ALTER TABLE rate_table_versions
        ADD CONSTRAINT no_overlap_active_version
        EXCLUDE USING gist (
            product_id WITH =,
            daterange(effective_from, COALESCE(effective_to, 'infinity'::date), '[]') WITH &&
        ) WHERE (status = 'active')
        """
    )

    # --- RBAC seed: permissions, admin/owner roles (granted every perm), and a
    # default admin user (username: admin / password: admin123 — change in any
    # real deployment). ---
    perms_table = sa.table(
        "permissions",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("resource", sa.String),
        sa.column("action", sa.String),
    )
    op.bulk_insert(
        perms_table,
        [{"code": c, "name": n, "resource": r, "action": a} for c, n, r, a in PERMISSIONS],
    )

    roles_table = sa.table(
        "roles",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("active", sa.Boolean),
    )
    op.bulk_insert(
        roles_table,
        [
            {"code": "admin", "name": "Administrator", "active": True},
            {"code": "owner", "name": "Owner", "active": True},
        ],
    )

    op.execute(
        """
        INSERT INTO role_permission (role_id, permission_id)
        SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
        WHERE r.code IN ('admin', 'owner')
        """
    )

    users_table = sa.table(
        "users",
        sa.column("username", sa.String),
        sa.column("full_name", sa.String),
        sa.column("password_hash", sa.String),
        sa.column("active", sa.Boolean),
    )
    op.bulk_insert(
        users_table,
        [
            {
                "username": "admin",
                "full_name": "Administrator",
                "password_hash": hash_password("admin123"),
                "active": True,
            }
        ],
    )

    op.execute(
        """
        INSERT INTO user_role (user_id, role_id)
        SELECT u.id, r.id FROM users u, roles r
        WHERE u.username = 'admin' AND r.code = 'admin'
        """
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE rate_table_versions "
        "DROP CONSTRAINT IF EXISTS no_overlap_active_version"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_cells_rate_table_version_id'), table_name='rate_cells')
    op.drop_table('rate_cells')
    op.drop_index(op.f('ix_policy_coverages_product_id'), table_name='policy_coverages')
    op.drop_index(op.f('ix_policy_coverages_policy_id'), table_name='policy_coverages')
    op.drop_table('policy_coverages')
    op.drop_table('user_role')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_rate_table_versions_product_id'), table_name='rate_table_versions')
    op.drop_table('rate_table_versions')
    op.drop_index(op.f('ix_product_rating_dimensions_product_id'), table_name='product_rating_dimensions')
    op.drop_table('product_rating_dimensions')
    op.drop_index(op.f('ix_policies_policy_number'), table_name='policies')
    op.drop_index(op.f('ix_policies_customer_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_customers_external_ref'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
