apiVersion: v1
kind: Namespace
metadata:
  name: dgc-web
---
apiVersion: v1
kind: Namespace
metadata:
  name: dgc-web-stg
---
apiVersion: v1
kind: Namespace
metadata:
  name: dgc-web-dev
---
# 🗝️ กุญแจสำหรับ Production (dgc-web)
apiVersion: v1
data:
  .dockerconfigjson: PLACEHOLDER_BASE64_DOCKERCONFIGJSON
kind: Secret
metadata:
  name: regcred
  namespace: dgc-web
type: kubernetes.io/dockerconfigjson
---
# 🗝️ กุญแจสำหรับ Staging (dgc-web-stg)
apiVersion: v1
data:
  .dockerconfigjson: PLACEHOLDER_BASE64_DOCKERCONFIGJSON
kind: Secret
metadata:
  name: regcred
  namespace: dgc-web-stg
type: kubernetes.io/dockerconfigjson
---
# 🗝️ กุญแจสำหรับ Develop (dgc-web-dev)
apiVersion: v1
data:
  .dockerconfigjson: PLACEHOLDER_BASE64_DOCKERCONFIGJSON
kind: Secret
metadata:
  name: regcred
  namespace: dgc-web-dev
type: kubernetes.io/dockerconfigjson