apiVersion: v1
kind: Namespace
metadata:
  name: dgc-web
---
apiVersion: v1
kind: Namespace
metadata:
  name: dgc-web-stg
---
apiVersion: v1
kind: Namespace
metadata:
  name: dgc-web-dev
---
# 🗝️ กุญแจสำหรับ Production (dgc-web)
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IucG9zdHdheS5jby50aCI6eyJ1c2VybmFtZSI6ImNhcmRpbmFsIiwicGFzc3dvcmQiOiJjYXJkaW5hbDBuQ2wwdWNsIiwiYXV0aCI6IlkyRnlaR2x1WVd3NlkyRnlaR2x1WVd3d2JrTnNNSFZqYkE9PSJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: dgc-web
type: kubernetes.io/dockerconfigjson
---
# 🗝️ กุญแจสำหรับ Staging (dgc-web-stg)
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IucG9zdHdheS5jby50aCI6eyJ1c2VybmFtZSI6ImNhcmRpbmFsIiwicGFzc3dvcmQiOiJjYXJkaW5hbDBuQ2wwdWNsIiwiYXV0aCI6IlkyRnlaR2x1WVd3NlkyRnlaR2x1WVd3d2JrTnNNSFZqYkE9PSJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: dgc-web-stg
type: kubernetes.io/dockerconfigjson
---
# 🗝️ กุญแจสำหรับ Develop (dgc-web-dev)
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IucG9zdHdheS5jby50aCI6eyJ1c2VybmFtZSI6ImNhcmRpbmFsIiwicGFzc3dvcmQiOiJjYXJkaW5hbDBuQ2wwdWNsIiwiYXV0aCI6IlkyRnlaR2x1WVd3NlkyRnlaR2x1WVd3d2JrTnNNSFZqYkE9PSJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: dgc-web-dev
type: kubernetes.io/dockerconfigjson