apiVersion: v1
kind: Namespace
metadata:
  name: dgc
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: dgc
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: PLACEHOLDER_BASE64_DOCKERCONFIGJSON
---
apiVersion: v1
kind: Namespace
metadata:
  name: dgc-stg
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: dgc-stg
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: PLACEHOLDER_BASE64_DOCKERCONFIGJSON
---
apiVersion: v1
kind: Namespace
metadata:
  name: dgc-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: dgc-dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: PLACEHOLDER_BASE64_DOCKERCONFIGJSON
